#!/bin/bash

set -eo pipefail

INSTALL_DIR="${0%/*}"
BREWFILE="$INSTALL_DIR/Brewfile"

function notify {
  echo [INSTALL] $@
}

function install_homebrew {
  path=$(which brew)
  if [ ! -x "$path" ]; then
    notify "brew installation not detected, installing brew (https://brew.sh/)..."
    set -x
    curl -fsSL 'https://raw.githubusercontent.com/Homebrew/install/master/install.sh' | sh /dev/stdin
    set +x
  fi
}

function install_brewfile {
  notify "installing brewfile packages..."
  set -x
  brew bundle --file "$BREWFILE"
  set +x
}

function install_kitty {
  path=$(which kitty)
  if [ ! -x "$path" ]; then
    notify "kitty installation not detected, installing kitty (https://sw.kovidgoyal.net/kitty/binary.html)..."
    set -x
    curl -L 'https://sw.kovidgoyal.net/kitty/installer.sh' | sh /dev/stdin
    set +x
  fi

}

install_homebrew
install_brewfile
install_kitty
